dist: bionic
language: node_js
node_js:
  - 12

addons:
  chrome: stable
  mariadb: '10.3'

services:
  - mariadb

cache:
  directories:
    - ./node_modules
    - ./fe/node_modules
    - ./be/node_modules
    - ./end2end/node_modules
    - ~/.npm
    - ~/.cache

before_install:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS fuyuko;'
  - mysql -uroot -e "USE mysql; ALTER USER 'root'@'localhost' IDENTIFIED BY 'root'; FLUSH PRIVILEGES;"
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
#  - cd be

#install:
#  - npm install

script:
  - echo 'Building & testing BE' &&
    cd be &&
    npm install &&
    npm run build &&
    npm run test &&
    cd ..
  - echo 'Building & testing FE' &&
    cd fe &&
    npm install &&
    npx ng test &&
    npx ng build &&
    cd ..
  - echo 'Building End 2 End1' &&
    cd end2end &&
    npm install &&
    cd ..
  - echo 'Running BE in background' &&
    cd be &&
    npm run exec &
    cd ..
  - echo 'Running FE in background' &&
    cd fe &&
    npx ng serve &
    cd ..
#  - kill $(jobs -p) || true
