dist: bionic
language: node_js
node_js:
  - 12

addons:
  chrome: stable

services:
  - mysql

cache:
  directories:
    - ./node_modules
    - ./fe/node_modules
    - ./be/node_modules
    - ./end2end/node_modules
    - ~/.npm
    - ~/.cache

before_install:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS fuyuko;'
  - mysql -uroot -e "USE mysql; UPDATE user SET password=PASSWORD('root') WHERE user='root'; FLUSH PRIVILEGES;" | mysql -u root
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
#  - cd be

#install:
#  - npm install

script:
  - cd be &&
    npm install &&
    npm run build &&
    npm run test &&
    cd ..
  - cd fe &&
    npm install &&
    npx ng test &&
    npx ng build &&
    cd ..
  - cd end2end &&
    npm install &&
    cd ..
  - cd be &&
    npm run exec &
    cd ..
#  - kill $(jobs -p) || true
