dist: bionic
language: node_js
node_js:
  - 12

addons:
  chrome: stable

services:
  - mariadb

cache:
  directories:
    - ./node_modules
    - ./fe/node_modules
    - ./be/node_modules
    - ./end2end/node_modules
    - ~/.npm
    - ~/.cache

before_install:
  - mariadb -e 'CREATE DATABASE IF NOT EXIST fuyuko;'
  - echo "USE mysql; UPDATE user SET password=PASSWORD('root') WHERE user='root'; FLUSH PRIVILEGES;" | mariadb -u root
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
#  - cd be

#install:
#  - npm install

script:
  - cd be &&
    npm install &&
    npm run build &&
    npm run test
  - cd ../fe &&
    npm install &&
    npx ng test &&
    npx ng build
  - cd ../end2end &&
    npm install &&
    $(npm bin)/print-env TRAVIS
  - kill $(jobs -p) || true
