version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd be
            - run: npm install
            - run: npm build
            - run: npm test
            - run: cd ..
            - run: cd fe
            - run: npm build
            - run: npm install
            - run: npx ng test
            - run: cd ..
            - run: cd end2end
            - run: npm install
workflows:
  build-and-test:
    jobs:
      - build-and-test