
apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot
  namespace: default

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: robot
  namespace: default
rules:
  - apiGroups: ["", "apps", "batch", "extensions"]
    resources: ["deployments", "services", "replicasets", "pods", "jobs", "cronjobs"]
    verbs: ["*"]


---


kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: robot
  namespace: default
subjects:
  - kind: ServiceAccount
    name: robot
    namespace: default
roleRef:
  kind: Role
  name: robot
  apiGroup: rbac.authorization.k8s.io