
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-loadbalancer-fuyuko-fe
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-pod-fuyuko-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
