

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubernetes-storage-slow-fuyuko-simple
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard


---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubernetes-storage-fast-fuyuko-simple
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-claim-fuyuko-simple
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kubernetes-storage-fast-fuyuko-simple
  resources:
    requests:
      storage: 3Gi
